version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: ./
    restart: always
    image: enquetes-node-api
    volumes: 
      - ./dist:/usr/src/enquetes-node-api/dist
    command: npm start
    ports:
      - "5050:5050"
    links:
      - mongo