services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/enquetes-node-api
    restart: always
    volumes: 
      - ./dist:/usr/src/enquetes-node-api/dist
      - ./package.json:/usr/src/enquetes-node-api/package.json
    command: bash -c "npm install --omit=dev && npm run debug"
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo